### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by bchartier** [georchestra/foncier#40]
Quelle est la licence applicable ?
Ce serait pas mal d'ajouter un fichier de licence à ce projet.

**Comment by bchartier** [comment]
Est-ce que c'est à l'EPF de choisir la licence ou est-ce que c'est Camtpocamp ?
Pour mes trucs j'ai tendance à utiliser la licence MIT (licence très simple).

**Comment by fvanderbiest** [comment]
> Est-ce que c'est à l'EPF de choisir la licence ou est-ce que c'est Camtpocamp ?

J'aurais tendance à dire que c'est au commanditaire de se décider sur ce point.

**Comment by bchartier** [comment]
ça me va.
Rudy une idée ? Besoin d'aide pour le choix ?

**Comment by fvanderbiest** [comment]
Des nouvelles sur ce point ?

**Comment by bchartier** [comment]
Je crois que je vais finir par faire le choix de la licence.

**Comment by mbessaguet** [comment]
Désolée, je ne reçois pas les échanges sur ce sujet, je n'ai donc pas vu votre interpellation, c'est Rudy qui vient de m'alerter. 
La licence EUPL nous semble adaptée.

**Comment by bchartier** [comment]
Je pense que ce ticket peut être fermé.
