### ISSUE TITLE
Accès à l'application sans le "/" final

### ISSUE THREAD

**Issue by bchartier** [georchestra/foncier#44]
Lorsque l'on ne met pas le "/" final dans l'URL de l'appli celle-ci ne fonctionne pas correctement :

1. la feuille de styles n'est pas chargée
2. l'action sur le bouton "submit" résulte en une erreur 404.

On devrait soit avoir un message d'erreur dès le chargement de l'appli si l'URL est mauvaise (genre 404) soit une appli qui supporte l'URL avec ou sans slash. De mon point de vue, il vaudrait mieux supporter le "/" final.

J'ai regardé le code source de l'appli en 10 minutes et je n'ai pas essayé de déployer et tester mes propositions de correction (donc je ne suis pas sûr de mon analyse) :

1. Pour le problème de chargement de CSS :
J'aurais tendance à penser que les URL renseignées dans les templates Jinja2 sont mal rédigées. Au lieu de mettre des pseudos chemins relatifs genre "/static/styles.css" (exemple https://github.com/ppige/foncier/blob/master/foncier/templates/index.html#L5) il faudrait utiliser les fonctions de Flask faites pour cela. Cf. url_for (exemple : http://flask.pocoo.org/docs/0.12/tutorial/templates/#layout-html).

2. Pour le problème d'erreur 404 sur le bouton submit
Je pense qu'il faut revoir la ligne suivante : https://github.com/ppige/foncier/blob/master/foncier/templates/index.html#L17
Il faudrait là aussi utiliser url_for comme dans cette exemple :
```html
<form action="{{ url_for('submit') }}" method="post">
```

**Comment by fvanderbiest** [comment]
> De mon point de vue, il vaudrait mieux supporter le "/" final.

C'est le fonctionnement souhaité, oui.
C'est presque au niveau du frontal qu'on devrait créer une redirection systématique /foncier -> /foncier/

**Comment by bchartier** [comment]
> De mon point de vue, il vaudrait mieux supporter le "/" final.

Je voulais dire : "De mon point de vue, il vaudrait mieux supporter **l'absence** du "/" final."

Flask le fait naturellement (à condition d'utiliser les fonctions de Flask) et ça éviterait d'avoir à configurer le frontal pour un truc sans valeur ajoutée.

**Comment by fvanderbiest** [comment]
Testé localement avec la composition, ça marche : https://github.com/ppige/foncier/pull/46
J'attends de voir derrière le security proxy...

**Comment by bchartier** [comment]
Ok, merci à toute l'équipe pour la mise en oeuvre de url_for.
Dis-moi quand ce sera déployé pour que je fasse des tests aussi.

**Comment by fvanderbiest** [comment]
C'est pas encore gagné ...

**Comment by fvanderbiest** [comment]
OK, on a maintenant https://dev.geopicardie.fr/foncier/ et https://dev.geopicardie.fr/foncier supportés grâce à `url_for`.

Mais je pense quand même qu'on devrait faire cette redirection systématique https://dev.geopicardie.fr/foncier -> https://dev.geopicardie.fr/foncier/ au niveau du frontal.

**Comment by bchartier** [comment]
Merci.
