### ISSUE TITLE
upgrade libs

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/foncier#47]
* Flask==0.11.1 --> 0.12.2
  * ldap3==2.1.1 --> 2.2.4
  * celery==4.0.0 --> 4.1.0

**Comment by bchartier** [comment]
Pour info, sur un autre projet sous Flask, Github nous a signalé une faille de sécurité sur la version 0.11.1. Nous sommes passés brutalement à la dernière version en date pour corriger cela.

Pour Celery, j'ai l'impression que les versions 4.0.0 et 4.1.0 ne sont pas compatibles avec les dernières versions de Python. Pas sûr d'avoir bien compris la raison de l'incompatibilité. Toujours est-il que pour Python 3.7.0 il semblerait qu'il faille également mettre à jour Celery avec une version plus récente.

**Comment by jeanpommier** [comment]
L'appli worker reposant sur l'image debian:stretch, qui utilise python 3.5 par défaut, il n'y a peut-être pas d'intérêt à passer à python 3.7 pour l'autre appli, non ?

**Comment by fvanderbiest** [comment]
Let's stay with python 3.5, it's easier & there's no use upgrading to my knowledge.

**Comment by jeanpommier** [comment]
then https://github.com/georchestra/foncier/pull/58 should be fine
